name: Build and upload docker images

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  backend:
    name: Build and publish images
    runs-on: ubuntu-latest
    environment: dockerhub
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN_SECRET }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push skandha image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_ACCESS_TOKEN_USERNAME }}/aa-playground:skandha-${{ github.sha }}
            ${{ secrets.DOCKER_HUB_ACCESS_TOKEN_USERNAME }}/aa-playground:skandha-latest
